# Generated by Django 4.2.24 on 2025-09-08 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QQBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_character_id', models.BigIntegerField(blank=True, null=True)),
                ('main_character_name', models.CharField(blank=True, max_length=100)),
                ('corp_ticket', models.CharField(blank=True, max_length=100, verbose_name='军团Ticket')),
                ('qq', models.CharField(max_length=20, verbose_name='QQ号')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qqbinding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QQ 绑定',
                'verbose_name_plural': 'QQ 绑定',
            },
        ),
    ]
