[program:beat]
command = C:\Users\yilifaer\aa-dev\.venv\Scripts\celery.EXE -A myauth beat
directory = C:\Users\yilifaer\aa-dev\myauth
user = allianceserver
stdout_logfile = C:\Users\yilifaer\aa-dev\myauth/log/%(program_name)s.log
stderr_logfile = C:\Users\yilifaer\aa-dev\myauth/log/%(program_name)s.log
autostart = true
autorestart = true
startsecs = 10
priority = 998

[program:worker]
command = C:\Users\yilifaer\aa-dev\.venv\Scripts\celery.EXE -A myauth worker --pool=threads --concurrency=5 -n %(program_name)s_%(process_num)02d
directory = C:\Users\yilifaer\aa-dev\myauth
user = allianceserver
numprocs = 1
process_name = %(program_name)s_%(process_num)02d
stdout_logfile = C:\Users\yilifaer\aa-dev\myauth/log/%(program_name)s.log
stderr_logfile = C:\Users\yilifaer\aa-dev\myauth/log/%(program_name)s.log
autostart = true
autorestart = true
startsecs = 10
stopwaitsecs = 600
killasgroup = true
priority = 998



[eventlistener:memmon]
command = None -p worker_00=256MB -p gunicorn=256MB
directory = C:\Users\yilifaer\aa-dev\myauth
events = TICK_60
stdout_logfile = C:\Users\yilifaer\aa-dev\myauth/log/memmon.log
stderr_logfile = C:\Users\yilifaer\aa-dev\myauth/log/memmon.log

[group:myauth]
programs = beat,worker
priority = 999
