# Generated by Django 5.2.17 on 2026-09-25 10:28

import django.core.validators
import django.db.models.deletion
import qqbot.models
from django.conf import settings
from django.db import migrations, models

# Must match USER_STRIPES + QQ_STRIPES in qqbot/core/locks.py.
LOCK_ROWS = 128


def create_lock_rows(apps, schema_editor):
    Lock = apps.get_model("qqbot", "Lock")
    Lock.objects.bulk_create([Lock(pk=k) for k in range(LOCK_ROWS)], ignore_conflicts=True)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="General",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("basic_access", "QQ 绑定 - 成员：可以绑定自己的 QQ"),
                    ("manage", "QQ 绑定 - 管理员：可以在前台管理 QQ 群与绑定"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rules_text",
                    models.TextField(
                        blank=True,
                        default="加入联盟 QQ 群即表示你同意遵守群规，入群后请认真阅读群公告。\n· 禁止传播涉黄、涉赌、涉毒的内容，包括讨论、链接、图片和视频；\n· 禁止人身攻击、种族歧视、造谣诽谤，以及低俗、暴力或其他负面内容；\n· 禁止讨论政治话题，避免触及敏感内容。\n让我们一起维护健康、友好的交流环境。",
                        verbose_name="入群须知",
                    ),
                ),
                (
                    "card_format",
                    models.CharField(
                        default="[{corp_ticker}] {character_name} - {nickname}",
                        help_text="可用占位符：{corp_ticker} 军团简称、{alliance_ticker} 联盟简称、{character_name} 主角色名、{nickname} 昵称",
                        max_length=100,
                        verbose_name="群名片格式",
                    ),
                ),
                (
                    "code_ttl_minutes",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="验证码有效期（分钟）",
                    ),
                ),
                (
                    "roster_max_age_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="机器人超过这么多天没有上报某个群的成员名单，该群就不能再用于「老成员免验证」。",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(30),
                        ],
                        verbose_name="群成员名单有效期（天）",
                    ),
                ),
                (
                    "rebind_cooldown_hours",
                    models.PositiveSmallIntegerField(
                        default=24,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(720),
                        ],
                        verbose_name="换绑冷却（小时）",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "设置",
                "verbose_name_plural": "设置",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("recheck", "复查该 QQ"),
                            ("card", "群名片变化"),
                            ("recheck_all", "全部复查"),
                            ("groups", "群配置变化"),
                        ],
                        max_length=16,
                    ),
                ),
                ("qq", models.CharField(blank=True, db_index=True, max_length=11)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ("id",),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Lock",
            fields=[
                ("id", models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("actor_name", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("bind", "绑定"),
                            ("verify", "验证成功"),
                            ("claim_failed", "验证失败"),
                            ("confirm", "管理员确认"),
                            ("conflict", "冲突"),
                            ("conflict_resolved", "冲突解决"),
                            ("rebind", "换绑"),
                            ("unbind", "解绑"),
                            ("force_unbind", "强制解绑"),
                            ("nickname", "修改昵称"),
                            ("card", "修改群名片"),
                            ("code", "生成验证码"),
                            ("group", "修改群配置"),
                            ("config", "修改设置"),
                            ("user_deleted", "账号删除"),
                        ],
                        max_length=24,
                    ),
                ),
                ("qq", models.CharField(blank=True, db_index=True, max_length=11)),
                ("target_name", models.CharField(blank=True, max_length=150)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "操作记录",
                "verbose_name_plural": "操作记录",
                "ordering": ("-id",),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="BindCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qq",
                    models.CharField(
                        db_index=True,
                        max_length=11,
                        validators=[qqbot.models.validate_qq],
                    ),
                ),
                ("nickname", models.CharField(max_length=32)),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qqbot_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "验证码",
                "verbose_name_plural": "验证码",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="QQGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="群名称")),
                (
                    "group_id",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[qqbot.models.validate_qq],
                        verbose_name="群号",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("fixed", "固定群"), ("role", "身份组小群")],
                        default="fixed",
                        max_length=8,
                        verbose_name="类型",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, verbose_name="说明"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=100, verbose_name="排序"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "last_roster_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近一次名单上报"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "required_groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="只对身份组小群有效：属于其中任意一个组即可。",
                        related_name="+",
                        to="auth.group",
                        verbose_name="需要的 AA 组",
                    ),
                ),
            ],
            options={
                "verbose_name": "QQ 群",
                "verbose_name_plural": "QQ 群",
                "ordering": ("kind", "sort_order", "name"),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="Binding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qq",
                    models.CharField(
                        db_index=True,
                        max_length=11,
                        validators=[qqbot.models.validate_qq],
                        verbose_name="QQ 号",
                    ),
                ),
                ("nickname", models.CharField(max_length=32, verbose_name="昵称")),
                (
                    "status",
                    models.CharField(
                        choices=[("verified", "已验证"), ("trusted", "老成员免验证")],
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "verified_via",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("code", "验证码"),
                            ("manager", "管理员确认"),
                        ],
                        default="",
                        max_length=10,
                        verbose_name="验证方式",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="验证时间"
                    ),
                ),
                (
                    "card_override",
                    models.CharField(
                        blank=True,
                        help_text="留空则按设置里的格式自动生成。",
                        max_length=60,
                        verbose_name="管理员指定的群名片",
                    ),
                ),
                ("qq_changed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "verified_qq",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=11,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qqbot_binding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "QQ 绑定",
                "verbose_name_plural": "QQ 绑定",
                "default_permissions": (),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("status", "verified"), ("verified_qq", models.F("qq"))
                            ),
                            models.Q(
                                models.Q(("status", "verified"), _negated=True),
                                ("verified_qq__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="qqbot_verified_qq_in_sync",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qq", models.CharField(db_index=True, max_length=11)),
                ("seen_at", models.DateTimeField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster",
                        to="qqbot.qqgroup",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("group", "qq"), name="qqbot_unique_roster_entry"
                    )
                ],
            },
        ),
        migrations.RunPython(create_lock_rows, migrations.RunPython.noop),
    ]
