# Generated by Django 4.2.24 on 2025-09-08 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qqbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qqbinding',
            options={'verbose_name': 'QQ绑定', 'verbose_name_plural': 'QQ绑定'},
        ),
        migrations.AlterField(
            model_name='qqbinding',
            name='corp_ticket',
            field=models.CharField(blank=True, max_length=64, verbose_name='军团Ticket'),
        ),
        migrations.AlterField(
            model_name='qqbinding',
            name='main_character_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='主角ID'),
        ),
        migrations.AlterField(
            model_name='qqbinding',
            name='main_character_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='主角名称'),
        ),
        migrations.AlterField(
            model_name='qqbinding',
            name='nickname',
            field=models.CharField(max_length=64, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='qqbinding',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qq_binding', to=settings.AUTH_USER_MODEL),
        ),
    ]
