# Generated by Django 5.2.17 on 2026-09-25 15:30

import django.core.validators
import qqbot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("qqbot", "0002_bilingual_permission_names"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "default_permissions": (),
                "ordering": ("-id",),
                "verbose_name": "Audit log entry",
                "verbose_name_plural": "Audit log",
            },
        ),
        migrations.AlterModelOptions(
            name="bindcode",
            options={
                "default_permissions": (),
                "verbose_name": "Verification code",
                "verbose_name_plural": "Verification codes",
            },
        ),
        migrations.AlterModelOptions(
            name="binding",
            options={
                "default_permissions": (),
                "verbose_name": "QQ binding",
                "verbose_name_plural": "QQ bindings",
            },
        ),
        migrations.AlterModelOptions(
            name="config",
            options={
                "default_permissions": (),
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="qqgroup",
            options={
                "default_permissions": (),
                "ordering": ("kind", "sort_order", "name"),
                "verbose_name": "QQ group",
                "verbose_name_plural": "QQ groups",
            },
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("bind", "Bind"),
                    ("verify", "Verification succeeded"),
                    ("claim_failed", "Verification failed"),
                    ("confirm", "Confirmed by manager"),
                    ("conflict", "Conflict"),
                    ("conflict_resolved", "Conflict resolved"),
                    ("rebind", "Change QQ"),
                    ("unbind", "Unbind"),
                    ("force_unbind", "Force unbind"),
                    ("nickname", "Change nickname"),
                    ("card", "Change group nickname"),
                    ("code", "Generate verification code"),
                    ("group", "Change group settings"),
                    ("config", "Change settings"),
                    ("user_deleted", "Account deleted"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="binding",
            name="card_override",
            field=models.CharField(
                blank=True,
                help_text="Leave empty to generate it from the format in Settings.",
                max_length=60,
                verbose_name="Group nickname set by manager",
            ),
        ),
        migrations.AlterField(
            model_name="binding",
            name="nickname",
            field=models.CharField(max_length=32, verbose_name="Nickname"),
        ),
        migrations.AlterField(
            model_name="binding",
            name="qq",
            field=models.CharField(
                db_index=True,
                max_length=11,
                validators=[qqbot.models.validate_qq],
                verbose_name="QQ number",
            ),
        ),
        migrations.AlterField(
            model_name="binding",
            name="status",
            field=models.CharField(
                choices=[
                    ("verified", "Verified"),
                    ("trusted", "Trusted (already in group)"),
                ],
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="binding",
            name="verified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Verified at"
            ),
        ),
        migrations.AlterField(
            model_name="binding",
            name="verified_via",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("code", "Verification code"),
                    ("manager", "Confirmed by manager"),
                ],
                default="",
                max_length=10,
                verbose_name="Verified via",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="card_format",
            field=models.CharField(
                default="[{corp_ticker}] {character_name} - {nickname}",
                help_text="Placeholders: {corp_ticker} corporation ticker, {alliance_ticker} alliance ticker, {character_name} main character name, {nickname} nickname",
                max_length=100,
                verbose_name="Group nickname format",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="code_ttl_minutes",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="Verification code lifetime (minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="rebind_cooldown_hours",
            field=models.PositiveSmallIntegerField(
                default=24,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(720),
                ],
                verbose_name="Change QQ cooldown (hours)",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="roster_max_age_days",
            field=models.PositiveSmallIntegerField(
                default=7,
                help_text='If the bot has not reported a group\'s member list for this many days, that group no longer counts for "Trusted (already in group)".',
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="Member list max age (days)",
            ),
        ),
        migrations.AlterField(
            model_name="config",
            name="rules_text",
            field=models.TextField(
                blank=True,
                default="加入联盟 QQ 群即表示你同意遵守群规，入群后请认真阅读群公告。\n· 禁止传播涉黄、涉赌、涉毒的内容，包括讨论、链接、图片和视频；\n· 禁止人身攻击、种族歧视、造谣诽谤，以及低俗、暴力或其他负面内容；\n· 禁止讨论政治话题，避免触及敏感内容。\n让我们一起维护健康、友好的交流环境。",
                verbose_name="Group rules",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="kind",
            field=models.CharField(
                choices=[
                    ("recheck", "Recheck QQ"),
                    ("card", "Group nickname changed"),
                    ("recheck_all", "Recheck all"),
                    ("groups", "Group settings changed"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="qqgroup",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="qqgroup",
            name="group_id",
            field=models.CharField(
                max_length=11,
                unique=True,
                validators=[qqbot.models.validate_qq],
                verbose_name="Group number",
            ),
        ),
        migrations.AlterField(
            model_name="qqgroup",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Enabled"),
        ),
        migrations.AlterField(
            model_name="qqgroup",
            name="kind",
            field=models.CharField(
                choices=[("fixed", "Fixed group"), ("role", "Role group")],
                default="fixed",
                max_length=8,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="qqgroup",
            name="last_roster_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last member list report"
            ),
        ),
        migrations.AlterField(
            model_name="qqgroup",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Group name"),
        ),
        migrations.AlterField(
            model_name="qqgroup",
            name="required_groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Only for role groups: being in any one of these groups is enough.",
                related_name="+",
                to="auth.group",
                verbose_name="Required AA groups",
            ),
        ),
        migrations.AlterField(
            model_name="qqgroup",
            name="sort_order",
            field=models.PositiveIntegerField(default=100, verbose_name="Sort order"),
        ),
    ]
