# Generated by Django 5.2.17 on 2026-09-25 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qqbot", "0003_i18n_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="trusted_window_days",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="Members already in a group can bind without a verification code only during this many days after the group was added here. After that, everyone uses a code. 0 turns this off.",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(365),
                ],
                verbose_name="Trusted binding window (days)",
            ),
        ),
    ]
